# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Whack-A-Mob_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/lib" -mwindows -lalleg_s -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -ldinput -lddraw -ldxguid -lwinmm -ldsound  
INCS =  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/US/Desktop/MARINA/Classes/Computer Graphics/Dev-CppPortable/App/devcpp/include" 
BIN  = Whack-A-Mob.exe
CXXFLAGS = $(CXXINCS) -DALLEGRO_STATICLINK  
CFLAGS = $(INCS) -DALLEGRO_STATICLINK  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Whack-A-Mob.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Whack-A-Mob.exe" $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

Whack-A-Mob_private.res: Whack-A-Mob_private.rc 
	$(WINDRES) -i Whack-A-Mob_private.rc --input-format=rc -o Whack-A-Mob_private.res -O coff 
